<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="HomeHub home automation system">
    <meta name="author" content="Janne Juhala">
    <link rel="shortcut icon" href="/favicon.ico">
    <title>HomeHub - Open source home automation system</title>
    <link href="/lib/bs/css/bootstrap.min.css" rel="stylesheet">
    <link href="/lib/fa/css/font-awesome.min.css" rel="stylesheet">
    <link href="/lib/toastr/toastr.min.css" rel="stylesheet">
    <link href="/css/global.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">HomeHub</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
              <li><a href="/">Home</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Manage<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="/manage-actions/">Actions</a></li>
                  <li><a href="/manage-rules/">Rules</a></li>
                  <li><a href="/manage-commands/">Commands</a></li>
                  <li><a href="/manage-sensors/">Sensors</a></li>
                </ul>
              </li>
              <li><a href="/history/">History</a></li>
              <li><a href="/log/">Log</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <?php if ($this->inc_cont_in_head) : ?>
    <div id="wrap">
    <div class="container" id="main">
    <?php endif; ?>
          
      <!-- Check if we need to show errors -->
      <?php if ($this->showError !== false) : ?>
        <?php foreach($this->errorMsg as $error) : ?>
          <div class="alert alert-danger">
            <i class="fa fa-exclamation-triangle fa-4x floleft"></i>
            <h4><strong><?=$error[0]?></strong></h4>
            <?=$error[1]?>
          </div>
        <?php endforeach; ?>
      <?php endif; ?>

      <!-- Check if we need to show notices -->
      <?php if ($this->showNotice !== false) : ?>
        <?php foreach($this->noticeMsg as $notice) : ?>
          <div class="alert alert-success">
            <i class="fa fa-check fa-4x floleft"></i>
            <h4><strong><?=$notice[0]?></strong></h4>
            <?=$notice[1]?>
          </div>
        <?php endforeach; ?>
      <?php endif; ?>
