


<div class="row">
	<div class="col-xs-6 col-md-7">
		<div class="page-header">
			<h1>Manage actions</h1>

		</div>
		<h2><small>Add, delete or edit actions</small></h2>
	</div>
	<div class="col-xs-6 col-md-5" style="margin-top:10px;float:right;">
		<div class="alert alert-info">
			<p>
				<strong>Actions</strong><br>
				- are the base element for any action you want to do.<br>
				- group one or more commands together (ie. turn TV off, turn XBMC playback off, turn lights off).<br>
				- can be automatically triggered.<br>
				- can be shown on the Dashboard at HomeHub main page.<br>
				- can be run via HTTP requests (see <a href="/api/">API</a>).<br>
				- can't have rules. Rules are added for every
				<a href="/manage-commands">command</a> separately
			</p>
		</div>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="padding5px nomargin">
			<i class="fa fa-bolt fa-lg padding5pxlr"></i>
			Current actions
		</h3>
	</div>
	<table class="table">
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Commands</th>
			<th>Triggers</th>
			<th>SoUI</th>
			<th>Notes</th>
			<th>Delete</th>
			<th>Run</th>
		</tr>

		<?php
			// Loop through all actions
			foreach ($this->actions_list as $action):
		?>
				<tr>
					<td><?=$action['actionID']?></td>
					<td><?=$action['name']?></td>
					<td><?=$action['commandList']?></td>
					<td><?=$action['triggers']?></td>
					<td><?=$action['showOnUI']?></td>
					<td><?=$action['notes']?></td>
					<td>
						<form action="/manage-actions/" method="POST">
						<input type="hidden" name="action" value="delete">
						<input type="hidden" name="action_id" value="<?=$action['actionID']?>">
						<button type="submit" class="a_del tippy btn btn-danger btn-sm" title="Delete action '<?=$action['name']?>'" data-actionid="<?=$action['actionID']?>" data-actionname="<?=$action['name']?>">
							<i class="fa fa-times-circle fa-lg"></i>
						</button>
						</form>
					</td>
					<td>
						<button class="a_run tippy btn btn-success btn-sm" title="Run action '<?=$action['name']?>'" data-actionid="<?=$action['actionID']?>" data-actionname="<?=$action['name']?>">
							<i class="fa fa-play-circle fa-lg"></i>
						</button>
					</td>
				</tr>
		<?php
			endforeach;
		?>

	</table>
</div>




<div class="row" style="margin-top:50px;">
	<div class="col-xs-6 col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="padding5px nomargin">
					<i class="fa fa-plus fa-lg padding5pxlr"></i>
					Add new action
				</h3>
			</div>
			<div class="panel-body">
				<form action="/manage-actions/" method="POST">
					<div class="form-group">
						<label>Action name</label>
						<i 
							onclick="bootbox.alert('<h3>Action name</h3>You can choose any action name you wish, it doesn\'t matter nor has to match with anything');" 
							class="fa fa-question-circle help-btn tippy"
							title="Click for help"
						>
						</i>
						<input class="form-control" name="name" placeholder="Action name">
					</div>
					<div class="form-group">
						<label>Commands</label>
						<i 
							onclick="bootbox.alert('<h3>Action\'s commands</h3>Write all commands you want to execute with this action here. Separate with |. Check available commands from \'Quickly check available commands and triggers\'-section (Name-column) next to \'Add new action\'-section.<br>Example: cmd1|lights1off|TVon|cmd4');" 
							class="fa fa-question-circle help-btn tippy"
							title="Click for help"
						>
						</i>
						<input class="form-control" name="commandList" placeholder="cmd1name|cmd2name|cmd3name|...">
					</div>
					<div class="form-group">
						<label>Triggers</label>
						<i 
							onclick="bootbox.alert('<h3>Action\'s triggers</h3>Optional. Write all sensors here you want to execute  this action with. Separate with |. Check available triggers from \'Quickly check available commands and triggers\'-section (cmd_name-column) next to \'Add new action\'-section.<br>Example: brightness1|door2|button2<br>Every time sensor value changes it executes the action where the sensor is set as trigger.<br>For actions linking to time-based commands which you\'d like to schedule, use * as trigger. This way it\'s triggered once every minute');" 
							class="fa fa-question-circle help-btn tippy"
							title="Click for help"
						>
						</i>
						<input class="form-control" name="triggers" placeholder="sensor1id|sensor2id|sensor3id|...">
					</div>
					<div class="checkbox">
						<label><input type="checkbox" name="showOnUI">Show on dashboard</label>
					</div>
					
					<div class="form-group">
						<label>Notes</label>
						<textarea rows="4" name="notes" class="form-control">...</textarea>
					</div>
					<button type="submit" class="btn btn-primary">Add</button>
				</form>
			</div>
		</div>
	</div>

	<div class="col-xs-6 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="padding5px nomargin">
					<i class="fa fa-list-ul fa-lg padding5pxlr"></i>
					Available commands and triggers
				</h3>
			</div>
			<div class="panel-body">
				<ul class="nav nav-tabs">
					<li class="active"><a href="#quicklist-commands" data-toggle="tab">Commands</a></li>
					<li><a href="#quicklist-triggers" data-toggle="tab">Triggers</a></li>
				</ul>

				<div class="tab-content">
					<div class="tab-pane active" id="quicklist-commands">
						<table class="table limit-table">
							<tr>
								<th class="col-md-1">#</th>
								<th>Name</th>
								<th>Command</th>
								<th>Rule list</th>
								<th>Notes</th>
								<th class="col-md-1">Run</th>
							</tr>

							<?php
								// Loop through all actions
								foreach ($this->commands_list as $command):
							?>
									<tr>
										<td><?=$command['commandID']?></td>
										<td><?=$command['name']?></td>
										<td><?=$command['command']?></td>
										<td><?=$command['ruleList']?></td>
										<td><?=$command['notes']?></td>
										<td>
											<button class="c_run tippy btn btn-success btn-sm" title="Run command '<?=$command['name']?>'" data-actionid="<?=$command['commandID']?>" data-actionname="<?=$command['name']?>">
												<i class="fa fa-play-circle fa-lg"></i>
											</button>
										</td>
									</tr>
							<?php
								endforeach;
							?>

						</table>
					</div>
					<div class="tab-pane" id="quicklist-triggers">
						<table class="table limit-table">
							<tr>
								<th class="col-md-1">#</th>
								<th>Name</th>
								<th>cmd_name</th>
								<th>Last update</th>
								<th class="col-md-1">Show On UI</th>
								<th>Notes</th>
							</tr>

							<?php
								// Loop through all actions
								foreach ($this->sensors_list as $sensor):
							?>
									<tr>
										<td><?=$sensor['sensorID']?></td>
										<td><?=$sensor['name']?></td>
										<td><?=$sensor['cmd_name']?></td>
										<td><?=$sensor['lastUpdate']?></td>
										<td><?=$sensor['showOnUI']?></td>
										<td><?=$sensor['notes']?></td>
									</tr>
							<?php
								endforeach;
							?>

						</table>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>
