


<div class="row">
	<div class="col-xs-6 col-md-7">
		<div class="page-header">
			<h1>Manage commands</h1>
			<h2><small>Add, delete or edit commands</small></h2>
		</div>
		
	</div>
	<div class="col-xs-6 col-md-5" style="margin-top:10px;float:right;">
		<div class="alert alert-info">
			<p>
				<strong>Commands</strong><br>
				- are the elements which contain one command which will be sent over 433MHz RF.
				- can have rules. To make a new rule, see <a href="/manage-rules/">rules</a>.
				- can be run via HTTP requests (see <a href="/api/">API</a>).<br>
				- can't be automatically triggered directly. Use <a href="/manage-actions/">actions</a> for that.
			</p>
		</div>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="padding5px nomargin">
			<i class="fa fa-bolt fa-lg padding5pxlr"></i>
			Current commands
		</h3>
	</div>
	<table class="table">
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Command</th>
			<th>Rule list</th>
			<th>Notes</th>
			<th>Delete</th>
			<th>Run</th>
		</tr>

		<?php
			// Loop through all commands
			foreach ($this->commands_list as $command):
		?>
				<tr>
					<td><?=$command['commandID']?></td>
					<td><?=$command['name']?></td>
					<td><?=$command['command']?></td>
					<td><?=$command['ruleList']?></td>
					<td><?=$command['notes']?></td>
					<td>
						<form action="/manage-commands/" method="POST">
						<input type="hidden" name="action" value="delete">
						<input type="hidden" name="id" value="<?=$command['commandID']?>">
						<button type="submit" class="a_del tippy btn btn-danger btn-sm" title="Delete action '<?=$command['name']?>'" data-actionid="<?=$command['commandID']?>" data-actionname="<?=$command['name']?>">
							<i class="fa fa-times-circle fa-lg"></i>
						</button>
						</form>
					</td>
					<td>
						<button class="c_run tippy btn btn-success btn-sm" title="Run action '<?=$command['name']?>'" data-actionid="<?=$command['actionID']?>" data-actionname="<?=$command['name']?>">
							<i class="fa fa-play-circle fa-lg"></i>
						</button>
					</td>
				</tr>
		<?php
			endforeach;
		?>

	</table>
</div>




<div class="row" style="margin-top:50px;">
	<div class="col-xs-6 col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="padding5px nomargin">
					<i class="fa fa-plus fa-lg padding5pxlr"></i>
					Add new command
				</h3>
			</div>
			<div class="panel-body">
				<form action="/manage-commands/" method="POST">
					<div class="form-group">
						<label>Command name</label>
						<i 
							onclick="bootbox.alert('<h3>Commands name</h3>You can choose any action name you wish as long as it\'s not longer than 100 characters. Short names are suggested as the command-list will otherwise get very long for actions that have many commands');" 
							class="fa fa-question-circle help-btn tippy"
							title="Click for help"
						>
						</i>
						<input class="form-control" name="name" placeholder="Command name">
					</div>
					<div class="form-group">
						<label>Command</label>
						<i 
							onclick="bootbox.alert('<h3>Commands</h3>This is the command that will be sent to the Arduino-server which will then send it over 433MHz RF. You can have multiple commands (separated with ;) but that is not recommended! Actions are usually used to have multiple commands executed at the same time.');" 
							class="fa fa-question-circle help-btn tippy"
							title="Click for help"
						>
						</i>
						<input class="form-control" name="command" placeholder="l1on">
					</div>
					<div class="form-group">
						<label>Rule list</label>
						<i 
							onclick="bootbox.alert('<h3>Commands\'s rule list</h3>Optional.<br>Write all the rules here (rule name) you want to apply to this command. Separate with |. You can write as many rules as you wish as long as the total length is under 300 characters. You can manage the rules on the Manage rules page. All these rules must pass for command to be sent.');" 
							class="fa fa-question-circle help-btn tippy"
							title="Click for help"
						>
						</i>
						<input class="form-control" name="rules" placeholder="door1closed|hour>7|hour<16|...">
					</div>
					
					<div class="form-group">
						<label>Notes</label>
						<textarea rows="4" name="notes" class="form-control"></textarea>
					</div>
					<button type="submit" class="btn btn-primary">Add</button>
				</form>
			</div>
		</div>
	</div>

	<div class="col-xs-6 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="padding5px nomargin">
					<i class="fa fa-list-ul fa-lg padding5pxlr"></i>
					Available rules
				</h3>
			</div>
			<table class="table limit-table">
				<tr>
					<th class="col-md-1">#</th>
					<th>Rule Name</th>
					<th>Sensor Name</th>
					<th>Rule list</th>
					<th>Value</th>
					<th>Notes</th>
				</tr>

				<?php
					// Loop through all actions
					foreach ($this->rules_list as $rule):
				?>
						<tr>
							<td><?=$rule['ruleID']?></td>
							<td><?=$rule['ruleName']?></td>
							<td><?=$rule['sensorName']?></td>
							<td><?=$rule['rule']?></td>
							<td><?=$rule['value']?></td>
							<td><?=$rule['notes']?></td>
						</tr>
				<?php
					endforeach;
				?>
			</table>
		</div>
	</div>
</div>
