<div class="row">
	<div class="col-xs-6 col-md-7">
		<div class="page-header">
			<h1>Manage actions</h1>

		</div>
		<h2><small>Add, delete or edit actions</small></h2>
	</div>
	<div class="col-xs-6 col-md-5" style="margin-top:10px;float:right;">
		<div class="alert alert-info">
			<p>
				<strong>Actions</strong><br>
				- are the base element for any action you want to do.<br>
				- group one or more commands together (ie. turn TV off, turn XBMC playback off, turn lights off).<br>
				- can be automatically triggered.<br>
				- can be shown on the Dashboard at HomeHub main page.<br>
				- can be run via HTTP requests (see <a href="/api/">API</a>).<br>
				- can't have rules. Rules are added for every
				<a href="/manage-commands">command</a> separately
			</p>
		</div>
	</div>
</div>

<h2>Current actions</h2>




<h2>Add new action</h2>

