<div class="jumbotron">
	<h1>Dashboard</h1>

	<h3>Sensors</h3>
	<div class="row">
		<div class="col-xs-6 col-md-2">

		</div>
	</div>

	<h3>Actions</h3>
	<div class="row">
		<div class="col-xs-6 col-md-2">

		</div>
	</div>
</div>

<h2>Quick links</h2>
<p>
	...
</p>


<h2>Log</h2>
<p>
	Shows last 15 lines, auto-update every 2 seconds. <a href="/log/">Full log »</a>
</p>
<div class="well">
	Log here...
</div>